import { Button } from "@/components/ui/button";
import { Coffee } from "lucide-react";
import Image from "next/image";
import Link from "next/link";

export const metadata = {
  title: "Cafe Web Application",
  description: "Generated by create next app",
};

export default function Utama() {
  return (
    <div className="relative bg-muted flex min-h-svh flex-col items-center justify-center gap-6 p-6 md:p-10">
      <h1 className="text-3xl font-bold">Welcome to Cafe Web Application</h1>{" "}
      <Coffee size={48} />
      <div className="">
        <Button variant="">
          <Link href="/home">Start</Link>
        </Button>
      </div>
    </div>
  );
}
